### ISSUE TITLE
Service Catalog based on K8s

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#12]
Provide services based on the infrastructure managed by K8s

- [x] Explore about Service Catalog #31  
- [x] Try helm on k3s with krustlet #32
- [x] Try minibroker with Helm and k3s #35
- [x] Try gcp-service-broker on k3s  #33

**Comment by jiayihu** [comment]
Steps involved in provisioning a service, from https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/#usage:

1. Listing the managed services and Service Plans available from a service broker/registry.
2. Provisioning a new instance of the managed service.
3. Istantiate the managed service.
4. Connect the service into the service/application.

**Comment by jiayihu** [comment]
The Open Service Broker API doesn't define provisioning a service means. It could just be allocating more database space. In fedra case, we could pull WASM modules from registry and instantiate Pods if possible, otherwise vendor cloud services could be used.
