### ISSUE TITLE
Configure the PIs

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#19]
- [x] Install the OS #18 
- [x] Setup automated configuration management #20
- [x] Setup basic K8s cluster #21
