### ISSUE TITLE
Implement a Rust Open Service Broker

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#39]
The difficulty lies probably in integrating with other k8s tools like Helm, which are written in Go.

- [x] Implement basic OSB #40 
- [x] Provision within the k3s cluster #41
- [ ] Support helm charts #42

The alternative would be learning Go and customizing minibroker but would require much more time. Learning to write an OSB is probably needed anyway when a IoT broker is going to be needed.
