### ISSUE TITLE
Implement flood prediction ML model 

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#51]
- [x] Read environmental monitoring literature #50
- [x] Find and preprocess data to a final dataset #57
- [x] Implement a local machine learning model #52
- [x] Compile the ML model for WASM #53
- [ ] Run the WASM ML training model in Cloud #55
- [x] Run the WASM ML inference model in k3s #56
- [x] Investigate how to stream data to the cluster #54
