### ISSUE TITLE
Create the final application

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#61]
- [x] Connect the application and Akri instances #62 
- [x] Connect the application and ML model in Krustlet #63 
- [x] Generate samples from dataset distribution #64 
- [x] Save sensor data to Gcloud #65 
- [x] Save latest rainfall data in local key-value storage #70
