### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#7]
Currently the code panics on error, it should instead improve error handling collecting the different error struct in a single struct

- [x] Define a unique error that includes all wasmi errors
- [ ] Minimize usage of `.unwrap` and `.expect`
- [ ] Return proper CoAP response codes for errors implemented as "separate response" (RFC 7252 5.2.2).
